version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    platform: linux/amd64
    image: mysql:8.0
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=zeineb
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
volumes:
  data:
